package com.zimolab.monacofx.monaco.editor

/**
 * JS中对应类的接口名称
 */
object JsAPIs {
    object Editor {
        const val CREATE = "create"
        const val IS_READY = "isReady"
        const val GET_LANGUAGES = "getLanguages"
        const val GET_OPTIONS = "getOptions"
        const val GET_OPTION = "getOption"
        const val ADD_ACTION = "addAction"
        const val REMOVE_ACTION = "removeAction"
        const val ADD_COMMAND = "addCommand"
        const val UPDATE_OPTIONS = "updateOptions"
        const val FOCUS = "focus"
        const val AUTO_LAYOUT = "autoLayout"
        const val SET_TEXT = "setText"
        const val GET_TEXT = "getText"
        const val GET_CURRENT_LANGUAGE = "getCurrentLanguage"
        const val SET_CURRENT_LANGUAGE = "setCurrentLanguage"
        const val SET_SCROLL_LEFT = "setScrollLeft"
        const val SET_SCROLL_TOP = "setScrollTop"
        const val SET_SCROLL_POSITION = "setScrollPosition"
        const val SET_SCROLL_POSITION_XY = "setScrollPositionXY"
        const val GET_ACTION = "getAction"
        const val GET_CONTENT_HEIGHT = "getContentHeight"
        const val GET_CONTENT_WIDTH = "getContentWidth"
        const val GET_LAYOUT_INFO = "getLayoutInfo"
        const val GET_LINE_DECORATIONS = "getLineDecorations"
        const val GET_OFFSET_FOR_COLUMN = "getOffsetForColumn"
        const val GET_SCROLL_HEIGHT = "getScrollHeight"
        const val GET_SCROLL_LEFT = "getScrollLeft"
        const val GET_SCROLL_TOP = "getScrollTop"
        const val GET_SCROLL_WIDTH = "getScrollWidth"
        const val GET_SCROLLED_VISIBLE_POSITION = "getScrolledVisiblePosition"
        const val GET_SELECTION = "getSelection"
        const val GET_SELECTIONS = "getSelections"
        const val GET_SUPPORTED_ACTIONS = "getSupportedActions"
        const val GET_TARGET_AT_CLIENT_POINT = "getTargetAtClientPoint"
        const val GET_TOP_FOR_LINE_NUMBER = "getTopForLineNumber"
        const val GET_TOP_FOR_POSITION = "getTopForPosition"
        const val GET_VALUE = "getValue"
        const val GET_VISIBLE_COLUMN_FROM_POSITION = "getVisibleColumnFromPosition"
        const val GET_VISIBLE_RANGES = "getVisibleRanges"
        const val HAS_TEXT_FOCUS = "hasTextFocus"
        const val HAS_WIDGET_FOCUS = "hasWidgetFocus"
        const val LAYOUT_CONTENT_WIDGET = "layoutContentWidget"
        const val LAYOUT_OVERLAY_WIDGET = "layoutOverlayWidget"
        const val POP_UNDO_STOP = "popUndoStop"
        const val PUSH_UNDO_STOP = "pushUndoStop"
        const val RENDER = "render"
        const val RESTORE_VIEW_STATE = "restoreViewState"
        const val SAVE_VIEW_STATE = "saveViewState"

        const val REVEAL_LINE = "revealLine"
        const val REVEAL_LINE_IN_CENTER = "revealLineInCenter"
        const val REVEAL_LINE_IN_CENTER_IF_OUTSIDE_VIEWPORT = "revealLineInCenterIfOutsideViewport"
        const val REVEAL_LINE_NEAR_TOP = "revealLineNearTop"

        const val REVEAL_LINES = "revealLines"
        const val REVEAL_LINES_IN_CENTER = "revealLinesInCenter"
        const val REVEAL_LINES_IN_CENTER_IF_OUTSIDE_VIEWPORT = "revealLinesInCenterIfOutsideViewport"
        const val REVEAL_LINES_NEAR_TOP = "revealLinesNearTop"

        const val REVEAL_POSITION = "revealPosition"
        const val REVEAL_POSITION_IN_CENTER = "revealPositionInCenter"
        const val REVEAL_POSITION_IN_CENTER_IF_OUTSIDE_VIEWPORT = "revealPositionInCenterIfOutsideViewport"
        const val REVEAL_POSITION_NEAR_TOP = "revealPositionNearTop"

        const val REVEAL_RANGE = "revealRange"
        const val REVEAL_RANGE_AT_TOP = "revealRangeAtTop"
        const val REVEAL_RANGE_IN_CENTER = "revealRangeInCenter"
        const val REVEAL_RANGE_IN_CENTER_IF_OUTSIDE_VIEWPORT = "revealRangeInCenterIfOutsideViewport"
        const val REVEAL_RANGE_NEAR_TOP_IF_OUTSIDE_VIEWPORT = "revealRangeNearTopIfOutsideViewport"

        const val SET_POSITION = "setPosition"
        const val SET_SELECTION = "setSelection"
        const val SET_SELECTIONS = "setSelections"
        const val SET_VALUE = "setValue"
        const val TRIGGER = "trigger"
        const val EXECUTE_EDITS = "executeEdits"
        const val GET_MODEL = "getTextModel"
        const val DISPOSE = "dispose"
        const val SET_THEME = "setTheme"
        const val GET_THEME = "getTheme"
        const val GET_BUILTIN_THEMES = "getBuiltinThemes"
        const val DEFINE_THEME = "defineTheme"
        const val LISTEN = "listen"
        const val UNLISTEN = "unlisten"
        const val IS_LISTENED = "isListened"
    }

    object TextModel {
        const val GET_READY = "onReady"
        const val DISPOSE = "dispose"
        const val IS_DISPOSED = "isDisposed"
        const val GET_OPTIONS = "getOptions"
        const val GET_VERSION_ID = "getVersionId"
        const val GET_ALTERNATIVE_VERSION_ID = "getAlternativeVersionId"
        const val SET_VALUE = "setValue"
        const val GET_VALUE = "getValue"
        const val GET_VALUE_LENGTH = "getValueLength"
        const val GET_VALUE_IN_RANGE = "getValueInRange"
        const val GET_VALUE_LENGTH_IN_RANGE = "getValueLengthInRange"
        const val GET_CHARACTER_COUNT_IN_RANGE = "getCharacterCountInRange"
        const val GET_LINE_COUNT = "getLineCount"
        const val GET_LINE_CONTENT = "getLineContent"
        const val GET_LINE_LENGTH = "getLineLength"
        const val GET_LINES_CONTENT = "getLinesContent"
        const val GET_EOL = "getEOL"
        const val GET_END_OF_LINE_SEQUENCE = "getEndOfLineSequence"
        const val GET_LINE_MIN_COLUMN = "getLineMinColumn"
        const val GET_LINE_MAX_COLUMN = "getLineMaxColumn"
        const val GET_LINE_FIRST_NON_WHITESPACE_COLUMN = "getLineFirstNonWhitespaceColumn"
        const val GET_LINE_LAST_NON_WHITESPACE_COLUMN = "getLineLastNonWhitespaceColumn"
        const val VALIDATE_POSITION = "validatePosition"
        const val MODIFY_POSITION = "modifyPosition"
        const val VALIDATE_RANGE = "validateRange"
        const val GET_OFFSET_AT = "getOffsetAt"
        const val GET_POSITION_AT = "getPositionAt"
        const val GET_FULL_MODEL_RANGE = "getFullModelRange"
        const val FIND_MATCHES = "findMatches"
        const val FIND_NEXT_MATCH = "findNextMatch"
        const val FIND_PREVIOUS_MATCH = "findPreviousMatch"
        const val GET_WORD_AT_POSITION = "getWordAtPosition"
        const val GET_WORD_UNTIL_POSITION = "getWordUntilPosition"
        const val GET_LINE_DECORATIONS = "getLineDecorations"
        const val GET_LINES_DECORATIONS = "getLinesDecorations"
        const val GET_DECORATIONS_IN_RANGE = "getDecorationsInRange"
        const val NORMALIZE_INDENTATION = "normalizeIndentation"
        const val UPDATE_OPTIONS = "updateOptions"
        const val DETECT_INDENTATION = "detectIndentation"
        const val PUSH_STACK_ELEMENT = "pushStackElement"
        const val POP_STACK_ELEMENT = "popStackElement"
        const val PUSH_EDIT_OPERATIONS = "pushEditOperations"
        const val PUSH_EOL = "pushEOL"
        const val APPLY_EDITS = "applyEdits"
        const val SET_EOL = "setEOL"
        const val IS_ATTACHED_TO_EDITOR = "isAttachedToEditor"
    }
}